name: Sync files to Azure DevOps

on:
  push:
    paths:
      - '**/*'

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get install git -y

    - name: Clone Azure DevOps repository
      run: |
        git clone https://DeveloperRamMicasa:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/DeveloperRamMicasa/MicasaWebsite/_git/MicasaWebsite
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

    - name: Copy files to Azure DevOps repository
      run: |
        shopt -s extglob
        cp -r !(MicasaWebsite) MicasaWebsite/
        cd MicasaWebsite
        git config --global user.email "azrdeveloper_ram1@outlook.com"
        git config --global user.name "RamkumarDev6978"
        git add .
        git commit -m "Sync files from GitHub"
        git push https://DeveloperRamMicasa:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/DeveloperRamMicasa/MicasaWebsite/_git/MicasaWebsite
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT 
